-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.adverts
(
    advert_id integer NOT NULL DEFAULT nextval('adverts_advert_id_seq'::regclass),
    car_id integer NOT NULL,
    date_posted date NOT NULL,
    seller_id integer NOT NULL,
    CONSTRAINT advert_pk PRIMARY KEY (advert_id)
);

CREATE TABLE IF NOT EXISTS public.bids
(
    bid_id integer NOT NULL DEFAULT nextval('bids_bid_id_seq'::regclass),
    advert_id integer NOT NULL,
    buyer_id integer NOT NULL,
    bid_price double precision NOT NULL,
    bid_date date NOT NULL,
    bid_status character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bid_pk PRIMARY KEY (bid_id)
);

CREATE TABLE IF NOT EXISTS public.buyers
(
    buyer_id integer NOT NULL DEFAULT nextval('buyers_buyer_id_seq'::regclass),
    buyer_name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying COLLATE pg_catalog."default",
    city_id integer NOT NULL,
    CONSTRAINT buyer_pk PRIMARY KEY (buyer_id)
);

CREATE TABLE IF NOT EXISTS public.car_products
(
    car_id integer NOT NULL DEFAULT nextval('car_products_car_id_seq'::regclass),
    brand character varying COLLATE pg_catalog."default" NOT NULL,
    car_mode character varying COLLATE pg_catalog."default" NOT NULL,
    body_type character varying COLLATE pg_catalog."default" NOT NULL,
    prod_year integer NOT NULL,
    price double precision NOT NULL,
    CONSTRAINT car_pk PRIMARY KEY (car_id)
);

CREATE TABLE IF NOT EXISTS public.cities
(
    city_id integer NOT NULL DEFAULT nextval('cities_city_id_seq'::regclass),
    city_name character varying COLLATE pg_catalog."default" NOT NULL,
    latittude double precision NOT NULL,
    longitude double precision,
    CONSTRAINT city_pk PRIMARY KEY (city_id)
);

CREATE TABLE IF NOT EXISTS public.sellers
(
    seller_id integer NOT NULL DEFAULT nextval('sellers_seller_id_seq'::regclass),
    seller_name character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying COLLATE pg_catalog."default",
    city_id integer NOT NULL,
    CONSTRAINT seller_pk PRIMARY KEY (seller_id)
);

ALTER TABLE IF EXISTS public.adverts
    ADD CONSTRAINT adverts_car_id_fkey FOREIGN KEY (car_id)
    REFERENCES public.car_products (car_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.adverts
    ADD CONSTRAINT adverts_seller_id_fkey FOREIGN KEY (seller_id)
    REFERENCES public.sellers (seller_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_advert_id_fkey FOREIGN KEY (advert_id)
    REFERENCES public.adverts (advert_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_buyer_id_fkey FOREIGN KEY (buyer_id)
    REFERENCES public.buyers (buyer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.buyers
    ADD CONSTRAINT buyers_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sellers
    ADD CONSTRAINT sellers_city_id_fkey FOREIGN KEY (city_id)
    REFERENCES public.cities (city_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;